### ISSUE TITLE
update composer.json

### ISSUE THREAD

**Issue by csae8092** [acdh-oeaw/arche-ingest#2]
/composer.json needs to be updated -> https://github.com/acdh-oeaw/arche-lib-ingest/releases/tag/1.7.1 ?

**Comment by zozlak** [comment]
Yes and no. No matter if the rule is `^1` or `^1.7.1` you have to run `composer update`. And in both cases you will get the right version of arche-lib-ingest.

So while `^1.7.1` would be semantically more correct, there is no difference in practice.

I guess the solution to your problem is "run `composer update` regularly"

**Comment by csae8092** [comment]
no, solution would be read carefully and watch for "^" ...
